name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload iOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-release
        path: build/ios/iphoneos/Runner.app
