name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Locate pubspec.yaml
        id: find_project
        run: |
          echo "PROJECT_DIR=$(find . -name pubspec.yaml -exec dirname {} \; | head -n 1)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd $PROJECT_DIR
          flutter pub get

      - name: Build APK
        run: |
          cd $PROJECT_DIR
          flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
